### ISSUE TITLE
Service won't start on Amazon Linux AMI release 2016.03

### ISSUE THREAD

**Issue by Breeze773** [aws/aws-cfn-resource-bridge#12]
I am attempting to test out the [CF example template](https://github.com/awslabs/aws-cfn-custom-resource-examples/blob/master/examples/mount/example.template) to use some cfn-init and cfn-signal commands to handle mounting and unmounting volumes within cloudformation.  
I have an rpm command to install the cfn-resource-bridge rpm in my cloudformation template.  The install of the code works, but when the service attempts to start I get the below error.  
I have installed the prereqs for this code.  It appears that this new package is not in the OS's default library path.  I'm not a python export so not sure how to fix this within my cloudformation templae.

This is the output in 
From /var/log/cfn-init.log

`2016-05-27 15:36:43,918 [DEBUG] Service output: Starting cfn-resource-bridge: Traceback (most recent call last):
  File "/opt/aws/bin/cfn-resource-bridge", line 18, in <module>
    from aws.cfn import bridge
ImportError: No module named aws.cfn
[FAILED]^M

2016-05-27 15:36:43,918 [ERROR] Error encountered during build of config2: Could not start cfn-resource-bridge
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 517, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 258, in build
    CloudFormationCarpenter._serviceTools[manager]().apply(services, changes)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/service_tools.py", line 167, in apply
    self._start_service(service)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/service_tools.py", line 198, in _start_service
    raise ToolError("Could not start %s" % service)
ToolError: Could not start cfn-resource-bridge
2016-05-27 15:36:44,017 [ERROR] -----------------------BUILD FAILED!------------------------
2016-05-27 15:36:44,020 [ERROR] Unhandled exception during build: Could not start cfn-resource-bridge
Traceback (most recent call last):
  File "/opt/aws/bin/cfn-init", line 171, in <module>
    worklog.build(metadata, configSets)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 118, in build
    Contractor(metadata).build(configSets, self)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 505, in build
    self.run_config(config, worklog)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 517, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 258, in build
    CloudFormationCarpenter._serviceTools[manager]().apply(services, changes)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/service_tools.py", line 167, in apply
    self._start_service(service)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/service_tools.py", line 198, in _start_service
    raise ToolError("Could not start %s" % service)
ToolError: Could not start cfn-resource-bridge
`
/etc/init.d/cfn-resource-bridge start
also outputs the same error.

Thanks in advance for any help on this.
-Chris

**Comment by emayssat-ms** [comment]
I had the same issue. I found that I needed to install python26 and made sure that the library was installed at the right location. I am now hitting other issues because cfn-resource-bridge was written a long while ago and apparently was not updated since then.

**Comment by hyandell** [comment]
This project has been archived. Please use CloudFormation’s native support for Custom Resources as documented at https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-custom-resources.html
